[build]
	base = "client/"
	command = "yarn build"
	publish = "dist/"
	ignore = "git diff --quiet HEAD HEAD~1"

[dev]
	command = "yarn --cwd client/ start"
	publish = "client/dist/"
	targetPort = 8080
	framework = "#custom"

[functions]
	directory = "functions/"

[[redirects]]
  	from = "/api/*"
	to = "/.netlify/functions/:splat"
	# status = 200
