[build]
	command = "cargo install wasm-pack && wasm-pack build && yarn && yarn --cwd ./client build"
	publish = "./client/dist/"

[functions]
	directory = "functions/"

[[redirects]]
	from = "/api/*"
	to = "/.netlify/functions/:splat"
	status = 200

